# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.4.0
_src_path: https://github.com/epics-containers/deployment-template-argocd
argocd_cluster: argus
argocd_server: argocd.diamond.ac.uk
cluster_name: argus
cluster_namespace: zsw36318
deployment_repo: https://github.com/srishtysajeev/t02-deployment
description: t02 IOC Instances and Services Deployment Repository for Argo CD
git_platform: github.com
github_org: srishtysajeev
ioc_group: t02
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: main
services_repo: https://github.com/srishtysajeev/t02-services
