# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.0.0/argocd-apps.schema.json

# This file configures an ArgoCD app of apps that represent a
# group of beamline or accelerator IOCs and services. The configuration of the
# services are in the separate repo indicated by repoURL.

# This repostory only controls which services and which versions of those
# services should be running on the cluster. It is recommended that this repo
# be updated by a CI/CD pipeline or configuration tools only.

project: zsw36318
destination:
  name: argus
  namespace: zsw36318
source:
  repoURL: https://github.com/srishtysajeev/t02-services
  targetRevision: main

services:
  # Each item is of the form:
  #   service: service name as it appears in K8S (statefulset/deployment name)
  #     targetRevision: optional override for targetRevision above
  #     repoURL: optional override for git repo to source the helm chart from
  #            the path is always services/<service> within that repo
  #     removed: set to true to remove the service from the cluster
  epics-pvcs:
  epics-opis:

ec_services:
  bl01t-mo-sim-01:
    enabled: true
    targetRevision: main
  # Services which have implemented support for an "enabled" parameter.
  # Each item is of the form:
  #   service: service name as it appears in K8S (statefulset/deployment name)
  #     targetRevision: optional override for targetRevision above
  #     repoURL: optional override for git repo to source the helm chart from
  #            the path is always services/<service> within that repo
  #     removed: set to true to remove the service from the cluster
  #     enabled: set to false to stop a service

  # example entry
  #   t02-ea-test-01:
  #     enabled: true
  #     targetRevision: main
